### ISSUE TITLE
how to answer enrollment questions before events happen? 

### ISSUE THREAD

**Issue by mashbourne** [IMSGlobal/caliper-spec#228]
Reporting use case: Show students that havent submitted their assignments yet (need to know they are in the class)

The `Organization` entities can be used to describe current state of entire org
Ex: `CourseSection` has [`Person`... ] as  `members`

The `Membership` entity can describe a single rostering action
Ex: `Person` is now `member` of `Organization`

We now have two separate ways that roster data can be sent, each with pros and cons. It would probably be nicer to have single unified way. And how does OneRoster encode this information? Are we aligned?

**Comment by joshuamcghee** [comment]
previously resolved, closing out issue
