### ISSUE TITLE
Spec review change recommendations (@ColinSmythe)

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-spec#260]
Per @ColinSmythe.  Formated for enhanced readability.
original: https://www.imsglobal.org/forum/caliper-analytics-document-library/156526

### Overall

This is an excellent piece of work. Well done Anthony.

However I have a large set of issues.

My main concern with this document is that it has combined the Information Model, Binding, Conformance and Best Practices aspects when these would normally, with good reason, be separated.  In many cases the Info Model description includes the JSON-LD binding details.

Conformance statements must not be included in this document. Most of the conformance statements address payload validity but IMS conformance is far broader.  It may be that a Sensor implementation is required to demonstrate support for ALL properties of an event, entity, etc. but this is different from payload validity.  A system will, in general, be required to demonstrate it support more than just the minimum payload constraints.  Then we have endpoint conformance.

### Structural

* The References section must be moved to be part of the Introduction section (this is standard IMS layout)
* Add a ‘Structure of the Rest of this Document’ as a subsection to the Introduction section (this is standard IMS layout)
* Restructure the ‘About this Document’ section to conoirm to IMS standard layout
* Add a subsection to the Introduction that summarises the key changes between 1.0/1.1 and states the backwards compatibility implications. This must include a summary of deprecated features
* Only the Basic Metric Profile should be described in this document.  All of the other Metric Profiles information must go into a separate document (in time that document may itself become more than one document)
* For the Info Model there must be a table that provides the formal definitions of the primitive types used e.g. UUID, DateTIme, etc.
* The JSON-LD binding must be described in terms of the OpenAPI specification. This provides a more complete way to describe the binding and is a machine-readable expression of the API.  This will ensure the full service is defined.

### General

* All of the Tables must be given a caption that includes a unique identifier and title
Section 1.2 (Terminology)
* The definition of the Endpoint should specifically state the use of HTTP.
Section 2.1 (The Caliper Event)
* Remove the last two sentences of the second para i.e. ‘The type value is …’ and ‘The assigned id value must …’.  These are addressed in the following table.
* In the Table the ‘Conformance’ column must become Multiplicity
* For the ‘action’ property this should be defined as a vocabulary with a link to Appendix A
* The properties that have the phrase ‘…object or coerced to a string …’ (e.g. object) need to be redefined.  Coercion is a feature of the JSON-LD binding.  The info model must be expressed independently of the binding form.
* There should be a UML visualization of the relationship between the Caliper Event and its subtypes
* There should be reference/link to Appendix B.

### Section 2.1 (The Caliper Entity)

* There should be a UML visualization of the relationship between the Caliper Entity and its subtypes.
* There should be reference/link to Appendix C.
* In the Table the ‘Conformance’ column must become Multiplicity
Section 2.3.1
* What is the relationship between the Basic Profile and the other profiles?

### Sections 2.3.2 -2.3.10 (Metric Profiles)
* Must be removed to a separate document
* For each Metric Profile the ‘Minimum Conformance’ definitions should be removed as these should be addressed in a separate Conformance Document
* In the ‘Supported Actions’ tables the ‘Conformance’ column must become Multiplicity and the entry of ‘Recommended’ changed to either Required/Optional.  Recommended is a best practice topic.

### Section 3 (Serialization of the Model)
This is the JSON-LD Binding description and so the Section should be renamed as such.  No other bindings are permitted.

### Section 4.1 (Behavior)
* This must be described as an info model i.e. removed references to JSON and arrays.  The ‘data’ property is a collection of Events and/or Entities.
* What is the logical service call? Is there just one service call that has end-to-end significance?
Section 4.2 (Envelop)
* This should be described as an info model as well as a JSON-LD binding. The envelop is a key part of the data model and conformance.

### Section 4.3 (Transport)
* Avoid mention of SSL and refer only to TLS (specifically v1.2)
* A Caliper sensor MUST support HTTP otherwise it will not be a Caliper Sensor (currently the doc states SHOULD).  This can be expanded as and when we support conformance for other messaging technologies.

### Section 5.1 (Endpoint Requirements)
All of the HTTP codes handling constraints should also be defined for the Sensor.  The usage of SHOULD is too vague because we will want to do conformance testing on these at both ends of the exchange.

### Appendix A
In the Table it may be better to provide the Term without the IRI and context.  Instead define the rule, with an example, for converting from the Term label to the IRI.

### Appendix B
In the Tables the ‘Conformance’ column must become Multiplicity

### Appendix C
In the Tables the ‘Conformance’ column must become Multiplicity

### Appendix E
Remove the reference to LTI 2.1 as this is to be deprecated. These roles originate in the LIS spec.

### Appendix G

The string lengths only need to define lengths for strings. Remove all those entries for properties of other types e.g. duration, datetime, etc. The layout for non-string data-types should be defined in the Primitive-types part of the Info Model.

### References
Rename the citation of ‘Whitepaper’ to ‘Caliper’.

**Comment by joshuamcghee** [comment]
closing as 1.1 is in full release and we are working on release for 1.2
