### ISSUE TITLE
More clarity around use of Event.federatedSession and the LtiSession entity

### ISSUE THREAD

**Issue by ViktorHaag** [IMSGlobal/caliper-spec#302]
We might want more clarity around our discussion of `Event.federatedSession` (in contrast to `Event.session`) and the `LtiSession` entity (and its properties).

Some things to note:

- The federated session is a way to capture "federated session" data that acts as a common reference point of meta-data for the platform(s) and tool(s) within the federation that are all jointly collecting user activity; each individual system in that federation probably has a _system-local_ session for the user when the user "arrives" to their context, and _that_ session data would get reported into `Event.session`; in cases where the system _also_ knows about a federated session context (for example, by initiating or receiving an LTI message), then it would probably report _that_ data in `Event.federatedSession`.

- The `LtiSession` is conceptually only one kind of federated session context that might exist; collections of Caliper aware systems might have _other_ means of federating activity that bind them together; in these cases, they may use `Event.federatedSession` to contain a simple `Session` entity, or they might seek to extend Caliper by adding a more specialized `Session` type entity (the way that the `LtiSession` is a more specialized entity).

- Systems should probably be careful not to mix data between the Event.Session system-local context and the Event.federatedSession federated system context... for example, in many systems, the way that an LMS (LTI platform) refers to a local User ID might be entirely distinct to the way that it represents that user's identity through _LTI_ (where it might have an entirely different identifier). Systems should probably take care to populate the properties of the `federatedSession` entity with values that are _bound to the federated context, and not the system local one_.

**Comment by joshuamcghee** [comment]
We believe that this is covered in the combination of the LTI Caliper spec doc and the Caliper 1.2 implementation guide
