### ISSUE TITLE
Response entity incorrectly lists DigitalResource as its supertype

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-spec#316]
The `Response` supertype is `Entity` and is described as such at

https://github.com/IMSGlobal/caliper-spec/blob/master/caliper-spec.md#c37-response

> #### Supertype
> [Entity](#entity)

However, the follow property description incorrectly lists `DigitalResource` as its supertype.  

> #### Properties
> [Response](#response) inherits all the properties and requirements defined for its supertype [DigitalResource](#digitalResource). Additional properties and requirements are described below:

This needs to be corrected as follows:

#### Properties
[Response](#response) inherits all the properties and requirements defined for its supertype [Entity](#entity). Additional properties and requirements are described below:

The tabular property list is correct.

**Comment by joshuamcghee** [comment]
The main spec doc looks to have these updates @bracken to validate if the cert suite, data model, and documentation followed suit
