### ISSUE TITLE
ToolLaunch profile: add payload examples for both LTI 1.1 and 1.3

### ISSUE THREAD

**Issue by mgylling** [IMSGlobal/caliper-spec#321]
From 20180717 WG call: 

Starting with LTI 1.3 messages bundles messages in complex ways; now its an encoded JWT, the implication of that is that some of the properties are complex objects. 

We should include 1.1 and 1.3 examples, and guidance on how to send those.

**Comment by joshuamcghee** [comment]
@bracken to add section in 1.2 caliper implementation guide describing differences between lti 1.1 and 1.3 payloads

**Comment by joshuamcghee** [comment]
this is resolved #544
