### ISSUE TITLE
ToolLaunch Profile typo: "at a given time and in a given context" phrase repeated in same sentence

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-spec#332]
ToolLaunchEvent description: 

><p>The <code>ToolLaunchEvent</code> models an interaction between a Person and external Tool (SoftwareApplication), at a given time and in a given context at a given time and in a given context.

The phrase "at a given time and in a given context" is repeated twice.

See https://github.com/IMSGlobal/caliper-spec/blob/develop/profiles/toollaunch/caliper-profile-toollaunch-v1p1.html.

**Comment by joshuamcghee** [comment]
cleaning up issues, this looks to have been resolved.
