### ISSUE TITLE
Create standalone Resource Management Profile

### ISSUE THREAD

**Issue by andrew-gardener** [IMSGlobal/caliper-spec#335]
Based on https://github.com/IMSGlobal/caliper-central/issues/138 

Current Development Branch: https://github.com/andrew-gardener/caliper-spec/tree/develop-profile/ResourceManagement-cc138

Pull Request: https://github.com/IMSGlobal/caliper-spec/pull/334 (TODO: need a develop branch on this repo to pull into... for now going to develop branch)

[View profile on raw.githack.com](https://raw.githack.com/andrew-gardener/caliper-spec/develop-profile/ResourceManagement-cc138/profiles/resource_management/caliper-profile-resource-management-v1p1.html)

**Comment by arwhyte** [comment]
Branch work merged to develop #342
