### ISSUE TITLE
FeedbackProfile: change points property name to scalePoints

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-spec#373]
The various Scale entities include a `points` data property defined as an  integer value used to determine the amount of points on the `Scale`.  I propose that we rename this property to `scalePoints` which will allow us, if needed at some later date, to add a generic `points` data property without reference to `Scale` entities.

**Comment by arwhyte** [comment]
@andrew-gardener -- what say you?

**Comment by andrew-gardener** [comment]
@arwhyte Sounds good to me. I think `itemCount` would also be fine (could be used in other collections in the future)

**Comment by arwhyte** [comment]
Resolved.
