### ISSUE TITLE
FeedbackProfile: change orderedSelection property name to isOrderedSelection

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-spec#374]
Adding "is" as a prefix provides a hint that the property value is of type boolean.

`orderSelection` to `isOrderedSelection`.  Also aligns with name format for the boolean `isTimeDependent` though, I must point out,  with `muted` (which should have been named `isMuted`).

**Comment by arwhyte** [comment]
@andrew-gardener -- what say you?

**Comment by andrew-gardener** [comment]
@arwhyte Sounds good to me 👍

**Comment by arwhyte** [comment]
Resolved.
